/// Currency constants and symbols for all countries
class CurrencyConstants {
  /// Map of currency codes to their symbols
  static const Map<String, String> currencySymbols = {
    'USD': '\$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'CNY': '¥',
    'KRW': '₩',
    'INR': '₹',
    'RUB': '₽',
    'BRL': 'R\$',
    'MXN': '\$',
    'CAD': 'C\$',
    'AUD': 'A\$',
    'CHF': 'CHF',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'TRY': '₺',
    'ILS': '₪',
    'ZAR': 'R',
    'EGP': '£',
    'SAR': '﷼',
    'AED': 'د.إ',
    'THB': '฿',
    'VND': '₫',
    'IDR': 'Rp',
    'MYR': 'RM',
    'PHP': '₱',
    'SGD': 'S\$',
    'HKD': 'HK\$',
    'TWD': 'NT\$',
    'ARS': '\$',
    'CLP': '\$',
    'COP': '\$',
    'PEN': 'S/',
    'UYU': '\$',
    'PYG': '₲',
    'BOB': 'Bs.',
    'VES': 'Bs.',
    'GTQ': 'Q',
    'HNL': 'L',
    'SVC': '\$',
    'NIO': 'C\$',
    'CRC': '₡',
    'PAB': 'B/.',
    'CUC': '\$',
    'DOP': 'RD\$',
    'HTG': 'G',
    'JMD': 'J\$',
    'TTD': 'TT\$',
    'BBD': 'Bds\$',
    'BSD': 'B\$',
    'BZD': 'BZ\$',
    'KYD': 'CI\$',
    'XCD': 'EC\$',
    'FJD': 'FJ\$',
    'GYD': 'G\$',
    'SBD': 'SI\$',
    'SRD': 'Sr\$',
    'TVD': '\$',
    'VUV': 'VT',
    'WST': 'WS\$',
    'TOP': 'T\$',
    'PGK': 'K',
    'KID': '\$',
    'BDT': '৳',
    'LKR': 'Rs',
    'NPR': '₨',
    'PKR': '₨',
    'AFN': '؋',
    'TJS': 'ЅМ',
    'TMT': 'T',
    'UZS': 'so\'m',
    'KZT': '₸',
    'KGS': 'сом',
    'AZN': '₼',
    'GEL': '₾',
    'AMD': '֏',
    'BYN': 'Br',
    'MDL': 'L',
    'UAH': '₴',
    'BAM': 'KM',
    'HRK': 'kn',
    'RSD': 'дин',
    'MKD': 'ден',
    'ALL': 'L',
    'ISK': 'kr',
    'RON': 'lei',
    'BGN': 'лв',
    'EEK': 'kr',
    'LVL': 'Ls',
    'LTL': 'Lt',
    'MZN': 'MT',
    'AOA': 'Kz',
    'CVE': '\$',
    'GMD': 'D',
    'GHS': '₵',
    'KES': 'KSh',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'LYD': 'ل.د',
    'SDG': '£',
    'SOS': 'S',
    'TZS': 'TSh',
    'UGX': 'USh',
    'CDF': 'FC',
    'BIF': 'FBu',
    'DJF': 'Fdj',
    'ERN': 'Nfk',
    'ETB': 'Br',
    'RWF': 'RF',
    'SCR': '₨',
    'MUR': '₨',
    'LSL': 'L',
    'NAD': 'N\$',
    'SZL': 'E',
    'ZMW': 'ZK',
    'ZWD': 'Z\$',
    'BWP': 'P',
    'MGA': 'Ar',
    'KMF': 'CF',
    'STN': 'Db',
    'SLL': 'Le',
    'LRD': '\$',
    'GNF': 'FG',
    'MWK': 'MK',
    'BND': 'B\$',
    'KHR': '៛',
    'JOD': 'د.أ',
    'IQD': 'ع.د',
    'LBP': 'ل.ل',
    'YER': '﷼',
    'OMR': 'ر.ع.',
    'QAR': 'ر.ق',
    'BHD': '.د.ب',
    'KWD': 'د.ك',
    'ANG': 'ƒ',
    'AWG': 'ƒ',
    'BMD': '\$',
    'GGP': '£',
    'IMP': '£',
    'JEP': '£',
    'MRO': 'UM',
    'SSP': '£',
  };

  /// Get currency symbol for a given currency code
  static String getCurrencySymbol(String currencyCode) {
    return currencySymbols[currencyCode] ?? currencyCode;
  }

  /// Format amount with currency symbol
  static String formatAmount(double amount, String currencyCode) {
    final symbol = getCurrencySymbol(currencyCode);
    return '$symbol${amount.toStringAsFixed(2)}';
  }
}

/// Time zone constants
class TimeZoneConstants {
  static const List<String> commonTimeZones = [
    'America/New_York',
    'America/Chicago',
    'America/Denver',
    'America/Los_Angeles',
    'America/Mexico_City',
    'America/Sao_Paulo',
    'America/La_Paz',
    'America/Bogota',
    'America/Lima',
    'America/Caracas',
    'America/Guayaquil',
    'America/Asuncion',
    'America/Montevideo',
    'America/Guatemala',
    'America/Tegucigalpa',
    'America/El_Salvador',
    'America/Managua',
    'America/Costa_Rica',
    'America/Panama',
    'America/Havana',
    'America/Santo_Domingo',
    'America/Puerto_Rico',
    'America/Toronto',
    'Europe/London',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Madrid',
    'Europe/Rome',
    'Europe/Moscow',
    'Asia/Tokyo',
    'Asia/Shanghai',
    'Asia/Seoul',
    'Asia/Singapore',
    'Asia/Hong_Kong',
    'Asia/Bangkok',
    'Australia/Sydney',
    'Australia/Melbourne',
    'Pacific/Auckland',
  ];
}

/// Country constants
class CountryConstants {
  static const Map<String, Map<String, String>> countries = {
    'US': {'code': 'US', 'name': 'Estados Unidos', 'currency': 'USD'},
    'MX': {'code': 'MX', 'name': 'México', 'currency': 'MXN'},
    'ES': {'code': 'ES', 'name': 'España', 'currency': 'EUR'},
    'AR': {'code': 'AR', 'name': 'Argentina', 'currency': 'ARS'},
    'BR': {'code': 'BR', 'name': 'Brasil', 'currency': 'BRL'},
    'CO': {'code': 'CO', 'name': 'Colombia', 'currency': 'COP'},
    'PE': {'code': 'PE', 'name': 'Perú', 'currency': 'PEN'},
    'CL': {'code': 'CL', 'name': 'Chile', 'currency': 'CLP'},
    'VE': {'code': 'VE', 'name': 'Venezuela', 'currency': 'VES'},
    'EC': {'code': 'EC', 'name': 'Ecuador', 'currency': 'USD'},
    'BO': {'code': 'BO', 'name': 'Bolivia', 'currency': 'BOB'},
    'PY': {'code': 'PY', 'name': 'Paraguay', 'currency': 'PYG'},
    'UY': {'code': 'UY', 'name': 'Uruguay', 'currency': 'UYU'},
    'GT': {'code': 'GT', 'name': 'Guatemala', 'currency': 'GTQ'},
    'HN': {'code': 'HN', 'name': 'Honduras', 'currency': 'HNL'},
    'SV': {'code': 'SV', 'name': 'El Salvador', 'currency': 'SVC'},
    'NI': {'code': 'NI', 'name': 'Nicaragua', 'currency': 'NIO'},
    'CR': {'code': 'CR', 'name': 'Costa Rica', 'currency': 'CRC'},
    'PA': {'code': 'PA', 'name': 'Panamá', 'currency': 'PAB'},
    'CU': {'code': 'CU', 'name': 'Cuba', 'currency': 'CUP'},
    'DO': {'code': 'DO', 'name': 'República Dominicana', 'currency': 'DOP'},
    'PR': {'code': 'PR', 'name': 'Puerto Rico', 'currency': 'USD'},
    'CA': {'code': 'CA', 'name': 'Canadá', 'currency': 'CAD'},
    'FR': {'code': 'FR', 'name': 'Francia', 'currency': 'EUR'},
    'DE': {'code': 'DE', 'name': 'Alemania', 'currency': 'EUR'},
    'IT': {'code': 'IT', 'name': 'Italia', 'currency': 'EUR'},
    'GB': {'code': 'GB', 'name': 'Reino Unido', 'currency': 'GBP'},
    'JP': {'code': 'JP', 'name': 'Japón', 'currency': 'JPY'},
    'CN': {'code': 'CN', 'name': 'China', 'currency': 'CNY'},
    'KR': {'code': 'KR', 'name': 'Corea del Sur', 'currency': 'KRW'},
    'AU': {'code': 'AU', 'name': 'Australia', 'currency': 'AUD'},
  };

  /// Get currency code for a country
  static String getCurrencyForCountry(String countryCode) {
    return countries[countryCode]?['currency'] ?? 'USD';
  }
}