name: Build frontend desktop

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/publish-frontend-desktop.yml'
      - '!**/readme.md'
      - '!**/.env'
      - '!frontend/android/**'
      - '!frontend/ios/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/publish-frontend-desktop.yml'
      - '!**/readme.md'
      - '!**/.env'
      - '!frontend/android/**'
      - '!frontend/ios/**'

defaults:
  run:
    working-directory: ./frontend

env:
  NODE_ENV: production
  VITE_API_URL: https://resto-api.iathings.com/api

jobs:
  build-tauri:
    if: ${{ false }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - name: Build Svelte app
        run: bun run build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './frontend'
          tauriScript: 'bun run tauri'
          args: ${{ matrix.args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app-${{ matrix.platform }}${{ matrix.args != '' && '-' || '' }}${{ matrix.args != '' && matrix.args || '' }}
          path: |
            frontend/src-tauri/target/release/bundle/
          retention-days: 7 