name: Publish frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/publish-frontend.yml'
      - '!**/readme.md'
      - '!**/.env'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/publish-frontend.yml'
      - '!**/readme.md'
      - '!**/.env'

defaults:
  run:
    working-directory: ./frontend

env:
  NODE_ENV: production
  VITE_API_URL: https://resto-api.iathings.com/api

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/resto-frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          build-args: |
            BUILD_API_URL=${{ env.VITE_API_URL }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/resto-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/resto-frontend:buildcache,mode=max 